### ISSUE TITLE
Scripts don't abort on error

### ISSUE THREAD

**Issue by bauen1** [ivandavidov/minimal#109]
Currently scripts will happily continue, even when a cd command or similiar failed.

This could be fixed by adding `set -e` to every buildscript.

**Comment by ivandavidov** [comment]
Yes, I've been thinking about this. Right now at least one script (kernel build script) may break if this feature is enabled. It's OK to use ``set -ex`` (enable fast fail + logging) everywhere, including in the initramfs area, but all of this has to be tested very thoroughly because there may be some edge cases. Some binaries rely on setting non-zero exit status (e.g. 'grep') which could lead to unexpected script failures. Actually that's the primary reason why I din't adopt this approach.

However, given the current code base, I agree that this feature is now really necessary.

**Comment by bauen1** [comment]
Anything wrapped in `$()` and `[]` shouldn't be affected.

**Comment by ivandavidov** [comment]
Let's hope it really is that way.

**Comment by ivandavidov** [comment]
This is the particular script line which bothers me:

https://github.com/ivandavidov/minimal/blob/master/src/02_build_kernel.sh#L92

There could be other places in other scripts where non-zero exit code is set by some binary. And these places are highly unlikely to be wrapped by ``$(...) or to be part of conditional checks.

Anyway, I propose we go with ``set -ex`` and fix the issues when they arise.

**Comment by bauen1** [comment]
I would only add `set -e`, because fast-logging clutters the output with a lot of unecessary stuff like echo commands, would that be ok for you ?

**Comment by ivandavidov** [comment]
Yes, that's fine. Anyone can set the ``-x`` flag explicitly if/when needed.

**Comment by ivandavidov** [comment]
This enhancement has been implemented. I'll close it after some more tests.

**Comment by ivandavidov** [comment]
Some scripts fail unexpectedly in certain conditions:

* If there is no 'clean' target in Makefile. This is actually a bug and it has been fixed in all such scripts.
* The ``strip`` command is used on files that cannot be stripped, e.g. shell scripts. This has been fixed by temporarily disabling the fast-fail and then enabling it again.

Apart from that, the ``set -e`` flag works exactly as expected and it is really helpful when issues arise. I'm closing the issue.
