### ISSUE TITLE
busybox 1.27.2 CVE-2017-16544 auto-complete vulnerability

### ISSUE THREAD

**Issue by bauen1** [ivandavidov/minimal#111]
Busybox 1.27.2 and older is vulnerable to injecting commands using esacpe codes in filenames.

http://cve.circl.lu/cve/CVE-2017-16544
https://git.busybox.net/busybox/commit/?id=c3797d40a1c57352192c6106cc0f435e7d9c11e8

**Comment by ivandavidov** [comment]
Thank you for pointing out this issue and the fix!

The good news is that MLL is not used in sensitive production environments, nor it is used in any production environments at all (as far as I know). The issue should be resolved with the next stable BusyBox version.

Meanwhile we can put some information in the README that currently there is a security issue in BusyBox and as result MLL has the same issue.

I am open for other suggestions.

**Comment by bauen1** [comment]
I do in fact plan to use MLL as a kexec-based bootloader to load linux from my usb drive.

We could apply the patch in https://github.com/ivandavidov/minimal/blob/master/src/06_get_busybox.sh , but that could break it for users using very old or very new versions of busybox.

**Comment by ivandavidov** [comment]
Regarding your idea to use MLL on USB - you will have to add some generic USB drivers and some specific USB hardware drivers in order to make this work. Right now there are no USB drivers in MLL enabled by default. BIOS/UEFI gives the control to the Syslinux on your USB device, which in turn loads the kernel/intramfs files in the RAM and finally Syslinux gives the control to the Linux kernel. The 'magic' part is that Syslinux knows the location of the kernel and initramfs files (basic USB support is handled by BIOS/UEFI) but afterwords the Linux kernel doesn't know anything about the hardware if it doesn't have appropriate hardware modules/drivers.

That said, if you intend to use MLL for some specific purpose, you could apply the patch to your specific source tree, since you will also need to do some additional modifications in order to add quite a few additional drivers in the kernel build process. Or add the drivers as loadable modules but this is another feature which has been in the queue for quite some time.

Regarding the BusyBox issue - one of the goals of the MLL project is to be as simple and understandable as possible. The source code simplicity is long gone, but using vanilla (unmodified) source code is still something that I'd like to keep in MLL.

**Comment by bauen1** [comment]
I want to use MLL on a cd to kexec the kernel on my usb drive for machines that don't support usb boot.

**Comment by ivandavidov** [comment]
Interesting use case!

I hope the default CD/DVD drivers in the kernel would be enough to detect your particular CD/DVD device, or otherwise you will have to add even more drivers in order to detect your CD/DVD device correctly.

Considering what I've seen so far from you, I have no doubt you will make it work!

**Comment by ivandavidov** [comment]
I'm leaving this issue opened until there is new stable BusyBox version.

**Comment by ivandavidov** [comment]
There is new BusyBox version and this can be closed now.
