### ISSUE TITLE
Question regarding overlay functionality

### ISSUE THREAD

**Issue by bootrino** [ivandavidov/minimal#148]
I can see a fair bit of code in there related to implementing overlay functionality including a switch_root.

Forgive me if I am talking without understanding the true context of what your code is doing.

Did you know that there is already simple and powerful overlay functionality built in to the initramfs system without any need for code or switch_root?

All you need to do is supply multiple initramfs files in syslinux.cfg, and the contents of the later ones overlay the previous.  

For example:

```
SERIAL 0
DEFAULT operatingsystem
LABEL operatingsystem
    KERNEL vmlinuz64 tce=/opt/tce noswap modules=ext4 console=tty0 console=ttyS0
    INITRD corepure64.gz,rootfs_overlay_initramfs.gz
```

In the case above (a syslinux.cfg for Tiny Core Linux), the files in rootfs_overlay_initramfs.gz overlay anything in corepure64.gz

I'm curious to know am I misunderstanding why you have your own overlay code?  Or could it be replaced simply with multiple initramfs files in the syslinux.cfg?

Incidentally it works the same with grub

**Comment by ivandavidov** [comment]
Having separate initramfs filesystems is interesting approach but it only provides logical separation of the same "rootfs" structure which is always loaded in the RAM.

The current MLL overlay functionality has the following architecture:

* Kernel + initramfs. This is the simplest scenario. Nothing interesting here.

* Kernel + initramfs + ``/minimal`` folder. In this case the content of the "/minimal" folder is overlayed in the initramfs structure. The benefit is that the content of the "/minimal" folder **is not** loaded in the RAM.

* Kernel + initramfs + ``/minimal.img`` file. In this case the "minimal.img" file is mounted and the internal content of the image file is overlayed in the initramfs structure. Once again, the benefit is that the content of the "/minimal.img" file **is not** loaded in the RAM. Another benefit is that "minimal.img" is treated as regular extX filesystem and can be detected and loaded from vfat formatted device. One limitation of the default overlayfs driver is that it can't merge vfat based file structures, hence the need for the workaround solution with the custom image.

Additional benefit of the overlay approach in MLL is that it recognizes whether the overlay media is writable (use the script ``generate_hdd.sh`` and then start MLL with ``qemu-bios.sh -hdd``). In this case MLL finds the overlay content on the external HDD, merges it with the initramfs structure and then virtually all HDD changes (with very few exceptions, e.g. the "/init" script cannot be changed because it is loaded and started before the overlayfs driver functionality is invoked) are persisted between reboots.

Of course, all of this has been implemented in MLL with quite a lot of custom logic in order to handle correctly the ro/rw use cases and in order to workaround the VFAT limitation of the overlayfs driver.

**Comment by bootrino** [comment]
Can I say firstly that this is a great project - I came here to find "what is the absolute minimum Linux system + busybox" and this seems to be heading in the right direction.

I don't want you to take this as criticism, it's just an observation, that the custom overlay functionality seems to take away from the "minimal" goal.  Persistence and overlays and customisation can be handled in other ways, and IMO those things are features of lightweight distros such as Alpine and TIny Core.

I guess I'm still questing to find that truly absolute minimal still usable kernel + busybox only.  MLL is close but not quite the most minimal.

What I'm really trying to do is to find a way to have the fastest and simplest possible booting Linux that can be used on a command line to see if it can replace things that Docker would otherwise be used for.  People seem to say that the benefit of Docker over virtual machines is that Docker is "more light weight".  I'm interested to know if that is really true, or if it is possible using qemu/kvm to be able to do most docker style tasks using virtual machines instead of containers.

An example use case for this ultra minimal distro that I am seeking is to be able to run a VM from the command line to carry out some processing task and exit on completion. qemu is able to map local folders of the host to the virtual machine, so I am imagining running a command which launches MLL, does some processing task, getting its input from the local folder, and then leaving the result in the local folder, then the VM exits itself by running poweroff.  

In an ideal world the default configuration of this tiny Linux build would work that way out of the box, and not pause to ask questions about configuration, thus all my questions in these issues about how to auto configure the display for use in a cloud/ssh/command line context and how to prevent the process from being paused during bootup.

Anyhow, just explaining my use case. Thank you for your great work!

**Comment by ivandavidov** [comment]
I just read the first 3 sentences in the email notification that I got. I suggest you are looking for something like [Minimal Linux Script](https://github.com/ivandavidov/minimal-linux-script).

Now I'll take some more time to read the rest of your comment. :)

**Comment by ivandavidov** [comment]
Another approach would be to edit the [init](https://github.com/ivandavidov/minimal/blob/62dd6a0b52cf1af494b744058185ff92be355f96/src/minimal_rootfs/init#L52) script in MLL and invoke shell instead of invoking the overlay functionality. All you need to do is this:

```
# This is the whole '/init' script.
/etc/01_prepare.sh
exec /bin/sh
```

Of course, you'll also have to remove the timeouts in the Syslinux configuration by using only one very simple configuration entry but you know how to do that anyway.
