### ISSUE TITLE
How can I disable the pauses on bootup?

### ISSUE THREAD

**Issue by bootrino** [ivandavidov/minimal#149]
I'm trying to make the boot as fast as possible.  The boot process pauses though to ask some questions.  How can I switch this off?  thanks.

```
[    3.307185] Freeing unused kernel memory: 1092K
Welcome to Minimal Linux Live (/init)
Most kernel messages have been suppressed.
Mounted all core filesystems. Ready to continue.

  Press empty key (TAB, SPACE, ENTER) or wait 5 seconds to continue with the
  overlay initialization process. Press any other key for PID 1 rescue shell
  inside the initramfs area.

Created folders for all critical file systems.
Copying the root file system to /mnt.
Searching available devices for overlay content.
  Found /minimal folder on device /dev/sr0.
  Device /dev/sr0 is mounted in read only mode.
  Overlay data from device /dev/sr0 has been merged.
Mount locations /dev, /sys, /tmp and /proc have been moved to /mnt.
Switching from initramfs root area to overlayfs root area.

  Press empty key (TAB, SPACE, ENTER) or wait 5 seconds to continue with the
  system initialization process. Press any other key for PID 1 rescue shell
  outside of the initramfs area.
```

**Comment by TechnologyClassroom** [comment]
I found some timers in these files:
src/minimal_boot/bios/boot/syslinux/syslinux.cfg
src/minimal_rootfs/init
src/minimal_rootfs/etc/03_init.sh

Change the timeout of syslinux and the value of read -t.

```
      -t timeout	time out and return failure if a complete line of input is
    		not read withint TIMEOUT seconds.  The value of the TMOUT
    		variable is the default timeout.  TIMEOUT may be a
    		fractional number.  If TIMEOUT is 0, read returns success only
    		if input is available on the specified file descriptor.  The
    		exit status is greater than 128 if the timeout is exceeded
```

**Comment by bootrino** [comment]
@TechnologyClassroom 

The pauses seem to be related to the overlay functionality.  

As mentioned here https://github.com/ivandavidov/minimal/issues/148 it would be good to be able to turn off the custom overlay functionality entirely, thereby removing the need to pause and ask a question during boot.  Or perhaps the default should be if there is overlay data then just go ahead and do whatever it needs to do to make the overlay happen.

**Comment by ivandavidov** [comment]
Assuming you already know how to handle the default Syslinux menu timeout, the next boot timeout (30 seconds) can be skipped by removing the ``vga=ask`` option from the respective configurations in the Syslinux configuration entries.

The other timeouts are related to the custom "rescue shell" functionalities which I have implemented just for demonstration purposes. @TechnologyClassroom has already provided the list of files where these timeouts are implemented. You can always simply remove the lines where the timeouts are implemented.

Of course, you'll have to "repackage" MLL after you implement your changes but I already know that you know how to do that. :)

**Comment by ivandavidov** [comment]
@TechnologyClassroom - regarding your last comment, the overlay detection functionality currently cannot be skipped. The only way to "skip" it would be to "repackage" MLL in a way that it doesn't produce overlay content. This can be done by commenting the [OVERLAY_TYPE](https://github.com/ivandavidov/minimal/blob/master/src/.config#L78) configuration property or by providing some weird value that means nothing to MLL. In this case there will be no overlay content to be loaded, but the overlay detection process in the initramfs will still be active and will search for overlay content (and of course no overlay content will be loaded since no overlay content would be present).

The MLL part of the initramfs structure is static. It will be really hard to implement configuration switches which remove the overlay detection process. However, I believe the MLL part of the initramfs structure is simple enough and very well documented, and it could be easily modified according to the specific needs.
