### ISSUE TITLE
Please give more insight in your error messages. Can't install extra packages.

### ISSUE THREAD

**Issue by pcs3rd** [ivandavidov/minimal#151]
so, trying to install all of the bundles, I get this error messages,
     Cannot continue - GLIBC is missing. Please buld GLIBC first.
I tried running 
     ./overlay_build.sh g*
which installed all glibc related packages, and still get the first error

**Comment by ivandavidov** [comment]
First of all - the overlay build system is not supported since there are a lot of dependencies and quirks that come directly from the host machine. This is why only few of the overlay bundles are enabled by default.

This error message means that the overlay build process cannot find the GLIBC libraries at the expected location. This may happen because the MLL build process hasn't been executed in advance, the failing bundle is expecting GLIBC somewhere else or in the meantime the GLIBC artifacts have been removed for some reason.

In order to investigate this issue further, you have to know which is the failing bundle and try to build it individually. You can check the build output in order to find out which is the last mentioned bundle before the failure.

**Comment by TechnologyClassroom** [comment]
Manually running ./overlay_build.sh g* would not affect the build process.  The scripts destroy the overlay folder.

Add all required packages to the config.

**Comment by ivandavidov** [comment]
More precisely - each overlay build "destroys" the result from the previous overlay build. This is done on purpose. The only exception is when you pass the ``--skip-clean`` flag to the ``overlay_build.sh`` script.

However, in this particular issue, the root cause of the problem is the missing GLIBC folder from the main MLL build. This can be "fixed" by building MLL before using the overlay build system.

As @TechnologyClassroom said, it would be much simpler and easier if you just add all bundles that you want to use in the main configuration file and then rebuild/repack MLL.

**Comment by pcs3rd** [comment]
I'm sorry, this is the first time building a Linux distro. So, I should build it THEN add packages to it? what config would I edit and what would I add to it. EG, What would I do if I wanted to install all of the packages? And is there a way to add custom packages from source? I want to turn this into a CPU-effective xmr mining os using a fork of cpuminer-multi that will work across machines. How would I do so @ivandavidov ?

**Comment by TechnologyClassroom** [comment]
@pcs3rd Meet all dependencies, edit [the .config file](https://github.com/ivandavidov/minimal/blob/master/src/.config) to choose overlays, and then build mll.

**Comment by pcs3rd** [comment]
@TechnologyClassroom ok, thank you. any way to run command after boot? if not thats ok.

**Comment by pcs3rd** [comment]
nevermind. it has a .(.) before it. Should probably rename that to something like mllbuild.config or something to prevent it from being ignored by file managers.

**Comment by TechnologyClassroom** [comment]
@pcs3rd Yes, you can.  Look at the init file and files in the etc folder:
src/minimal_rootfs/init
src/minimal_rootfs/etc/

**Comment by pcs3rd** [comment]
@TechnologyClassroom Ok, can I change that AFTER compiling? Or do I have to do that while building the image?

**Comment by TechnologyClassroom** [comment]
@pcs3rd Not sure, but look at [repackage.sh](https://github.com/ivandavidov/minimal/blob/master/src/repackage.sh).

**Comment by pcs3rd** [comment]
@TechnologyClassroom Looks like that will work. if not, I may be able to just restart. its not a big deal.

**Comment by ivandavidov** [comment]
@pcs3rd - even though MLL is an educational project, it is also a project which builds entire operating system from vanilla sources. You definitely need to understand some Linux internals and the internal structure of the MLL OS in order to make this project usable for your specific use case.

Most people just want to add some additional software in MLL from source code (e.g. vim, nano or virtually any other core Linux program) in which case it is enough to concentrate on the MLL's overlay build system and use the already existing bundle build scripts as reference for your own bundle that you want to include in MLL.

The simplest way to include already existing Linux binary in MLL is to put this binary in the [minimal_overlay/rootfs](https://github.com/ivandavidov/minimal/tree/master/src/minimal_overlay/rootfs) folder. In that case you don't have to deal with the overlay build process and all you need is to run the main MLL build process which will automatically include everything you've placed in this special folder.

**Comment by pcs3rd** [comment]
I have taken that approach with appimage platform in the rootfs. Where can I put extra libraries if I wanted to? could I just "add" an src folder to use make?

**Comment by ivandavidov** [comment]
Probably the least painful learning path is this one:

* Go through the [tutorial](https://github.com/ivandavidov/minimal/blob/master/src/the_dao_of_minimal_linux_live.txt). It explains the internals of the first version of MLL.
* Examine the [Minimal Linux Script](https://github.com/ivandavidov/minimal-linux-script) project and make sure you understand each line and its meaning.
* Only after that start poking MLL. The build scripts are well documented but you need to go on your own with the reverse engineering process. This process is a lot easier if you know the build sequence in advance and you know the purpose of each software piece in the puzzle.

Regarding your question - you can add library files in the "/lib" folder. That is, you go to the "minimal_overlay/rootfs" folder and there you create a "lib" subfolder where you add your precompiled libraries. The folder "minimal_overlay/rootfs" represents the root ("/") folder and whatever you put there will be overlayed with the already existing directory structure in the initramfs.

**Comment by pcs3rd** [comment]
Ok, I am bookmarking and closing this "issue" you guys have been a great help. I will make sure to remember. I have looked at all of dose files. Thank You!
