### ISSUE TITLE
Dummy questions. Or not so dommy

### ISSUE THREAD

**Issue by saymoncoppi** [ivandavidov/minimal#152]
Hello Ivan!
I'd like to ask some questions about the MLL, overlays and new flavors. But first of all thankyou for your hard work at the community.

So:
- Any plans to use musl or dietlib instead of glibc?
- Squashfs + rootfs to persistance changes 
- Add apt tools for easily installation new pkgs?
- Deliver a overlay with wifi drivers and wifi tools.
- Offer an overlay with xorg_core and fluxbox (or any other wm)

Im asking this kind of things bc I'd like to make something similar to MLL + Slax. As a Slide (Small lightweight incredible Desktop Edition) lol

Could you gimme the direction?
I already made an slax similar script including a debotstrap process, wipe and clean the trash but i cant reach a tiny size, my goals are make a beatiful boot splash and desktop, a control conter using lighttp+php and support for , Deb, Snap, AppImage, Flatpak

Tks for yor attention. Best regards

**Comment by TechnologyClassroom** [comment]
@saymoncoppi There is a similar, but different project based on musl called [Janus](https://github.com/JanusLinux/janus).

**Comment by ivandavidov** [comment]
Short summary before you read the rest - MLL is an educational project with main goal to provide simple, reliable and easy to understand build infrastructure which generates minimalistic Linux OS from vanilla (unmodified) sources. Everything else is out of the scope for this project.

**Q:** Any plans to use musl or dietlib instead of glibc?
**A:** There used to be an experimental ``musl`` based MLL but in the end it turned out that the whole process cannot be easily automated, because the musl headers kind of collide with the kernel headers. You can read more about this issue [here](http://blog.idzona.com/2016/01/the-future-of-minimal-linux-live.html). The interesting commits are [here](https://github.com/ivandavidov/minimal/commit/130ffa2cec787cdeacdba5a15b3ae7a7d9a296b6) and [here](https://github.com/ivandavidov/minimal/commit/1ca057ee0b86512a7e97f74baf5e06e54ce21084). Note the [hack](https://github.com/ivandavidov/minimal/commit/1ca057ee0b86512a7e97f74baf5e06e54ce21084#diff-247a63262f817300da3f6a812f1b5dadR26) with the C structures - this hack is different when you change the kernel/musl versions and this is why it cannot be easily automated.

Moreover, musl's general goal is to provide small, statically linked executables. It may be possible to use musl as general purpose C library (I haven't researched this topic) but in the general use case if you want to add executables directly in MLL, these executables must be statically linked since there is no C library layer which could handle the dynamic loading.

Moving to GNU C library was a strategic decision. First of all, by default MLL doesn't provide all GNU C shared obejcts and therefore the overall MLL size is still very small. The great benefit of using GNU C library is the fact that all standard software nowadays relies on the same GNU C library and dynamically linked executables can quite easily be invoked in MLL environment, provided that all shared object dependencies have been met. This opened the door for the "overlay bundles" (as I call them in MLL). You can put any standard executable file in MLL and it should run just fine.

MLL will continue to be based on GNU C library but it may be worth to research once again whether it is possible/worth to add another "MLL flavor", based on musl, even if there are no overlay bundles.

**Q:** Squashfs + rootfs to persistance changes
**A:** Squashfs - probably not, because this requires more drivers to be present in MLL. This has been implemented in @ladiko's fork [here](https://github.com/ladiko/minimal/blob/master/src/2_build_kernel.sh). BTW, this fork is great - it adds SquashFS and NTFS support, provides [USB instaler](https://github.com/ladiko/minimal/blob/master/src/create_boot_stick.sh) and thanks to this fork I learned how to handle the network device detection. Really great stuff!

Also, dealing with SquashFS requires some userland utilities which should be present on the build machine. This adds another layer of complexity on the host machine. One of the goals of the MLL project is to be as simple as possible. Dealing with SquashFS is possible, but it is not that simple.

Regarding the rootfs persistence - this is supported by MLL at the moment with the ``OverlayFS`` driver. The MLL's boot process detects if the overlay device is writable and in this case all file/folder changes (with very few exceptions) are persisted between reboots. However, since there is no USB installer at the moment, this functionality can only be observed/tested by using external HDD image which holds the whole overlay area. You can use the script [generate_hdd.sh](https://github.com/ivandavidov/minimal/blob/master/src/generate_hdd.sh) and then start MLL with the image attached to the VM as virtual HDD ([qemu-bios.sh -h](https://github.com/ivandavidov/minimal/blob/master/src/qemu-bios.sh)). In this case the overlay area from the external HDD will be detected first and since the HDD is writable, all changes will be persisted. Of course, the persisted changes will be "visible" only as long as the external virtual HDD is attached to the VM.

The same approach would work fine with USB flash drives (see issue #131) but this hasn't been implemented yet.

**Q:** Add apt tools for easily installation new pkgs?
**A:** Short and simple - no. The main goal of the MLL project is to provide simple enough build infrastructure which demonstrates what steps you should follow in order to build your own minimalistic Linux based OS from vanilla sources. Adding more software on top of MLL by using some package manager is commonly requested feature, but the MLL design doesn't allow that (at least not at the moment). First of all, the Linux kernel is very minimalistic and it doesn't support some functionalities (e.g. you can't run Docker in MLL, but there is an experimental branch for this feature). The second issue is that package managers require some specific file/folder structure to be present. The next issue is that some package managers use external binaries which are not provided by MLL (e.g. 'apt' invokes 'tar' with parameters that are not supported by BusyBox). Given all the complexity, it is simpler **not** to support package managers.

If you want to use some third-party software, you should choose another base OS, e.g. Ubuntu Mini edition or something similar.

**Q:** Deliver a overlay with wifi drivers and wifi tools.
**A:** This is commonly requested feature. The answer is that Wi-Fi drivers are designed for specific hardware and therefore there is no "common" way to provide generic drivers. This adds more complexity in the kernel build process but that's the easy part. The harder part is to find the sources for your particular driver, build these drivers as kernel modules and add them to MLL. You have one set of hardware pieces, I have another set of hardware pieces and Pen Jin Hong from China may have Wi-Fi hardware that no one has ever heard about with drivers provided from fourth-party company.

Short and simple - adding any hardware specific drivers/modules/tools in MLL is responsibility of the person who uses this particular hardware. My goal is to provide the generic MLL build infrastructure + some example overlay bundles which demonstrate how MLL can be "upgraded".

You may add the drivers that you need in your own overlay bundle and I'd be happy to merge your overlay bundle in the MLL project, but I definitely won't be adding any specific drivers/tools in the MLL project by myself.

**Q:** Offer an overlay with xorg_core and fluxbox (or any other wm)
**A:** Pretty much the same answer. X implementations have tons of dependencies and the overall build process is highly unstable since your host machine has to meet all of the prerequisites for the build process. This can be automated but the process is enormously tedious and complex. Pretty much you have to build the entire world before you start building the X server. Providing X implementation in binary form (no need to build anything) is also difficult due to the huge amount of dependencies between the software pieces.

On day I may add some form of X overlay bundle but it won't be in the near future and most probably in the end it will work fine only on my machine. :)

**Comment by saymoncoppi** [comment]
Hello again Ivan! Tks for all answers.
Could you help me with another question? How can I wipe the /lib/modules to let only essencial? I mean, base sound, eth and video.

**Comment by ladiko** [comment]
After executing 1_get_kernel.sh, you can go to the folder with the extracted kernel ($WORK_DIR/kernel/linux-*) and execute `make menuconfig` and deselect all unwanted kernel modules: http://how-to.wikia.com/wiki/How_to_configure_the_Linux_kernel. Then before executing 02_build_kernel.sh, you should comment out the line 15 `make mrproper -j $NUM_JOBS` because otherwise it " Cleans up the kernel sources, including configuration files".

**Comment by ivandavidov** [comment]
In addition to the above answer, I'd like to add that by default MLL doesn't provide any kernel modules. You can take a look at the [kernel_modules](https://github.com/ivandavidov/minimal/tree/master/src/minimal_overlay/bundles/kernel_modules) overlay bundle which adds only the modules that are available in the default kernel configuration.

I recommend you follow the ``make menuconfig`` strategy and also enable the kernel_modules overlay bundle in the MLL ".config" file. In this way you will end up with customized MLL image which contains exactly the kernel modules you want.

**Comment by saymoncoppi** [comment]
Hello again Ivan! Tks for all answers again!!!

Im trying to mix some ideas:
- Make a Debian crhoot using debootstrap
- Including X core and openbox 
- Include latest wifi drivers (like slax does)
- Wipe the /lib/modules folder (like slitaz, core or puppy linux)

Nowadays, the harder part to me is wipe folder. I'v already asked at the slitaz forum about the magic to choose right modules but they doenst answer.

So again, tks for your attention!

**Comment by ivandavidov** [comment]
I don't think there are right or wrong modules to choose from (assuming we are still talking about kernel modules). If you know what hardware you are aiming at, it's easier to start from scratch and include just the corresponding kernel modules. If you are trying to "trim" already existing kernel module structure... well, in this case you are on your own, no matter what base distro you've been using.

**Comment by protonesso** [comment]
Build cross-toolchain for MLL, it allows link sofware with different libcs
