### ISSUE TITLE
Keyboard doesn't work

### ISSUE THREAD

**Issue by clar0193** [ivandavidov/minimal#161]
The system boots OK, but when I get to a shell prompt the keyboard doesn't work.  It works OK selecting a video mode, but when I get to the first "Press empty key..." prompt it does not work.  The messages scroll by too fast to read, and since the keyboard doesn't work I can't press SHIFT PAGEUP to view the screen or look at log files. :-/

I'm using a generic USB keyboard.  I tried both the 28-Jan-2018 ISO from the website and also building the current version from Github using the build_minimal_linux_live.sh script.  I grep'd the documentation directory for any information related to keyboards, but did not find anything.  I did not alter the config file before building.  Any suggestions will be appreciated.

**Comment by ivandavidov** [comment]
I assume you are trying MLL on **real** hardware. Unfortunately, minimalism comes at price and that price is the almost nonexistent hardware support in the Linux kernel. More precisely, there is no whatsoever additional USB support in MLL, apart from the stuff that has been enabled by default in the Linux kernel and that stuff isn't that much.

MLL is mostly and educational operating system and it has been designed to run flawlessly in virtual environments (e.g. QEMU, VirtualBox and VMware Workstation Player). However, wide hardware detection and providing proper device drivers have never been on the schedule and most probably they will never be, because that goes well beyond the "minimal" definition.

Thank you for trying MLL but if your goal is to have smoothly running small Linux based OS on **real** hardware, then you should try another OS which provides the kernel modules for your hardware.

**Comment by clar0193** [comment]
Thanks for the quick response.  You are correct, I was trying to run on actual hardware.  I have been doing Linux From Scratch builds, and I ran across your project while researching something related to LFS.

**Comment by bauen1** [comment]
You might have to enable USB 3.0 in the linux kernel .config.

**Comment by clar0193** [comment]
Thanks -- I'll try this when I find the time.
