### ISSUE TITLE
[Question / Idea] How to add support for gcc ?

### ISSUE THREAD

**Issue by Sejoslaw** [ivandavidov/minimal#166]
Hey <3

I'm thinking about making linux distro from scratch and I think MLL is the easiest for this type of things.
So my question is how can I add an overlay bundle for gcc (similar like 'make') ?
It would be great because than You could compile other software on MLL itself.

Also I would like to ask how to make an ISO installable (?). My point is that is it possible to create a script for automatic installation of MLL onto the hard drive ?

**Comment by ivandavidov** [comment]
Well, creating an operating system is not a simple task. You should be prepared to put **a lot** of efforts in your project.

Adding ``GCC`` is **out of the scope** for the MLL project. MLL is designed to be small and most of all simple. Now take a look at the [GCC dependencies](https://gcc.gnu.org/install/prerequisites.html) - in order to have GCC in MLL we have to build and prepare in advance all of the GCC dependencies first. And most of these dependencies have their dependencies as well (e.g. Perl). Are you willing to make proper list of all dependencies and create corresponding overlay bundles in MLL in order to prepare the playground for GCC? :)

Long story short - GCC is out of the picture. However, there some alternatives, e.g. [Go](https://github.com/ivandavidov/minimal/issues/155) and to some point [static-get](https://github.com/ivandavidov/minimal/issues/59).

Regarding the installer - MLL is really simple operating system and it requires only few files to run. There is a working installer in the overlay bundle [mll_utils](https://github.com/ivandavidov/minimal/tree/master/src/minimal_overlay/bundles/mll_utils) but it doesn't really work out of the box and it only handles BIOS machines. You can also refer to #131 and implement your own installer which follows the described steps.

If you know how UEFI works, you can install MLL on UEFI enabled machines as well. All you need to do is to put the UEFI enabled kernel (don't forget the initramfs file) in the EFI boot partition and set the UEFI boot manager to use the MLL kernel as boot stub. You can create a simple shell script to automate the process.

Currently I have no plans to add official installer in MLL because MLL is not designed to run on real hardware (see #162). Installing MLL on USB flash device is more realistic but even in this case you won't get anything useful because MLL is really small and it doesn't detect most of the hardware devices, including most of the USB devices.Perhaps you could do better with your OS project.

Feel free to ask more questions and/or raise other issues. I'll be happy to assist you!

Regards,
Ivan Davidov

**Comment by Sejoslaw** [comment]
Thanks for Your answer.
You helped me to think about few things which I forgot about (or never thought of) :)
