### ISSUE TITLE
kernel boot failed

### ISSUE THREAD

**Issue by abhimegha** [ivandavidov/minimal#183]
after building iso when i ru it is showing end kernel panic not syncing attempted to kill init exit

**Comment by ivandavidov** [comment]
There could be many reasons why your build is not running. After all this is an operating system and building an OS is never that easy. There are many host OS dependencies that you should meet and many software pieces that you should take care of.

That said, you should either provide much more detailed information about what's wrong or (better approach) you should spend some time and explore the internals of MLL, i.e. examine the scripts, read the tutorial and learn how the kernel/initrd work together. After that you should be able to figure out what's wrong.

**Comment by benoncoffee** [comment]
Posting this as a reference for people with similar problems. I'm having the same problem, both on real hardware and in a virtual machine:

![](https://github.com/benoncoffee/files/blob/master/images/screenshot.png?raw=true)

There's some information on this error in the [Gentoo knowledge base](https://wiki.gentoo.org/wiki/Knowledge_Base:Unable_to_mount_root_fs):

## Analysis
The panic informs that the Linux kernel is unable to:

 1. Detect the controller for the hard disk (a likely candidate if the message says unknown-block(0,0));
 2. Detect the partition because it does not have support for the partition type (less likely, but still possible);
 3. Mount the partition because it does not know how to access the file system (a likely candidate if the message gives a non-zero figure in the first number set, such as unknown-block(2,0));
 4. Detect the partition because the wrong device was passed in the boot loader configuration.

## Resolution

Boot with the old kernel (if available), or with a LiveCD, and open the kernel configuration:

    root #make menuconfig

 - Ensure that the controller chipset has been configured in the Linux kernel (and in-kernel, not as a module);
 - Ensure that the used file systems (such as ext2, ext3, ext4, ReiserFS, Btrfs, etc.) are configured in the Linux kernel (and built into the kernel, not as a module);
 - Ensure that, if you use root=UUID=..., you have built an initramfs when configuring the bootloader, see "Configuring the linux kernel" of your installation handbook
 - If running Gentoo as a Qemu guest, ensure that the virtio block drivers and PCI driver for virtio devices are enabled in the kernel (that is, CONFIG_VIRTIO_BLK=y and CONFIG_VIRTIO_PCI=y in the kernel configuration file).

I would expect that the last point would also hold when using VirtualBox. In my particular case, the first cause (a missing hard disk controller) seems most likely, based on the information in the Gentoo knowledge base. I don't have time to try this now.
