### ISSUE TITLE
Post run support to local hard drive installation

### ISSUE THREAD

**Issue by mckenziec** [ivandavidov/minimal#187]
First, excellent job. You can't understand how excited I was to find your project. Gentoo is great but man its not for the faint of heart.

I know this request is probably not what a live Linux distro is targeting, but there is the need for customized, base Linux that can be run live, then mount, partition and write a bootable copy to a hard drive. Maybe minimal doesn't need to explicitly support those final steps, but it could be a supported use case.

I was playing with trying to include a squashfs image with a minimal iso as a test. So I could boot into minimal, then mount/chroot my own file system that would be compatible with the minimal kernel. After booting it I was unable to locate/mount the physical hard drive (no /dev/sdaX or cd rom type device). 

Personally I'm looking for a boot strapping type of custom Linux build that I can run live but also install to a hard drive. I would add some post-boot scripting to partition the hard drive if it isn't yet, then mount squashds/unionfs images. e.g. a new / and /var/lib/snapd/snaps/ for a resulting running OS with files and snaps pre-installed and running, and they can be replaced with newer/different squashfs images when needed (however I get them on there).

I hope this isn't an inappropriate request. If it is I'm back to building Gentoo from scratch.

**Comment by ivandavidov** [comment]
Minimal Linux Live is really minimal in terms of functionality. It provides only what's in the default kernel configuration and only limited superset of config items that are necessary for the proper "overlayfs" functionality.

Your idea could be implemented as one or more additional overlay bundles, including a kernel rebuild that supports SquashFS. You can take a look at @ladiko's MLL fork [here](https://github.com/ladiko/minimal) which provides SquashFS support. Also, installing MLL should be easy enough since it is based on Syslinux and once you understand how Syslinux works, you can simply copy the necessary MLL files on your disk, run Syslinux there and you are done with the installation. The reason the "MLL installer" is not finished is because Syslinux has 32-bit library dependencies and MLL can't provide them in default 64-bit build mode. MLL has to be extended to support multi-arch (x86 and x86-64) before you have a working installer in MLL.

Note that you will also need a great bunch of other kernel configurations (e.g. USB support, specific vendor support, etc.) and you'll have to add all of that in the kernel or as loadable kernel modules. Minimalism comes with price and this price is the pretty minimal hardware support.

Currently there is no active plan to extend the MLL functionalities in these directions, but perhaps someone might be interested to implement them. I'll leave this issue open for a while.
