### ISSUE TITLE
Anaconda/mlflow bundle problem

### ISSUE THREAD

**Issue by frankmeten** [ivandavidov/minimal#192]
https://docs.anaconda.com/anaconda/install/linux/  _bash ~/Downloads/Anaconda3-2019.07-Linux-x86_64.sh_
https://mlflow.org/docs/latest/quickstart.html  **pip install mlflow**

this 2 bundles has no xxx.tar.gz file like JAVA_ARCHIVE=/home/ivan/Downloads/jdk-9.0.1_linux-x64_bin.tar.gz

how could we integrate the 2 bundles to minimal_linux_live.iso?

**Comment by ivandavidov** [comment]
MLL is an educational build infrastructure which allows you to build the minimum required components for functional Linux based operating system. That said, if you want to modify anything in MLL, the best way to do that is to examine the existing build scripts. There are many examples which demonstrate how to include additional software in MLL.

You should also have in mind that you'll have to provide all external dependencies for the software that you want to add, because MLL provides only basic console functionality + few additional bundles on top.

Perhaps the easiest way to integrate additional software in MLL is to add everything you want directly in the [minimal_overlay/rootfs](https://github.com/ivandavidov/minimal/tree/master/src/minimal_overlay/rootfs) directory or in subdirectories there. Then all your software will be available in the MLL runtime. The other option is to write your own overlay bundle. In the latter case you have to get familiar with the overlay structure in MLL which can be done by examining the overlay build scripts.
