### ISSUE TITLE
build_minimal_linux_live.sh - scheme missing (v 28-Jan-2018)

### ISSUE THREAD

**Issue by sarnobat** [ivandavidov/minimal#197]
What am I doing wrong here? I'm sure it's something simple.

# Release
`28-Jan-2018`
# Input
```
./build_minimal_linux_live.sh
```
# Output

```Executing script '00_clean.sh'.
*** CLEAN BEGIN ***
Cleaning up the main work area. This may take a while.
*** CLEAN END ***
Executing script '01_get_kernel.sh'.
*** GET KERNEL BEGIN ***
Downloading source file from '/media/me/unmirrored/trash/minimal-28-Jan-2018/src/source/'.
Saving source file in ''.
/media/me/unmirrored/trash/minimal-28-Jan-2018/src/source/: Scheme missing.
```

**Comment by ivandavidov** [comment]
Please try to build MLL with no modifications and see if the error is still there. Then I suggest you enable the ``USE_LOCAL_SOURCE`` property in the main ``.config`` file. In this way, you will be sure that the sources won't be downloaded again.

**Comment by sarnobat** [comment]
Thanks for the quick reply. I just tried the same thing on master, with `USE_LOCAL_SOURCE=true` and got the same thing:

```
$ ./build_minimal_linux_live.sh
Executing script '00_clean.sh'.
*** CLEAN BEGIN ***
Cleaning up the main work area. This may take a while.
*** CLEAN END ***
Executing script '01_get_kernel.sh'.
*** GET KERNEL BEGIN ***
Downloading source file from '/media/me/unmirrored/trash/minimal-linux-master/src/source/'.
Saving source file in ''.
/media/me/unmirrored/trash/minimal-linux-master/src/source/: Scheme missing.
```

The only other thing I can think of is that my .bashrc and .zshrc were doing something buggy. But I switched to `/bin/sh` which resulted in this similar output.

I'm assuming this works on your machine. I'm not sure what else could be different about mine.

**Comment by sarnobat** [comment]
I notice when `./common.sh` is called, there is no `$2` which is the target of the download, hence the empty path in the output `Saving source file in ''.`. Is this expected?

**Comment by ivandavidov** [comment]
Take a look at the source code.

https://github.com/ivandavidov/minimal/blob/master/src/01_get_kernel.sh#L17

The first argument is ``$DOWNLOAD_URL`` and the second argument is ``$SOURCE_DIR/$ARCHIVE_FILE``. I can only suspect that you have changed something on your local host OS environment which breaks the build process.

Although MLL provides full automation, the project is not intended for novice users. Have in mind that MLL is a well-tested product and it provides stable build infrastructure. Building an operating system is not an easy task and you have to be prepared that there are software prerequisites that you have to meet on your host OS. Also, you have to have experience with shell scripts, in order to be able to read them and learn from them. This means that you have to be prepared to deal with build issues and be able to track them. If you find this project difficult, I suggest you try [Minimal Linux Script](https://github.com/ivandavidov/minimal-linux-script) (MLS) first, before you continue with MLL.

**Comment by sarnobat** [comment]
Thanks for the information, I will try and troubleshoot it with what you've shared.

Closing. If anyone else encounters this issue I hope it's ok if they reopen it.
