### ISSUE TITLE
NTFS USB mount fail

### ISSUE THREAD

**Issue by gadd1** [ivandavidov/minimal#22]
Mounting NTFS USB drive fails with error : "failed: invalid argument" 

![ntfs_mount](https://cloud.githubusercontent.com/assets/7931117/12377951/9dad3b70-bd37-11e5-9e91-1660ca2c2b84.png)

didnt find where to configure in order to add ntfs support (if its possible at all..)

Thanks,

**Comment by ntpetrov** [comment]
Did you try with mount -t ntfs ?

**Comment by gadd1** [comment]
Tried it now, and i get "failed: no such device"
![2016-01-21_08-21-43](https://cloud.githubusercontent.com/assets/7931117/12473146/36f29c3e-c018-11e5-9735-dfc2a79605ec.png)

if the same USB is formatted as FAT32 it works fine ..

**Comment by ivandavidov** [comment]
This is not a bug, that's exactly how it is supposed to work. "Minimal Linux Live" is built with default kernel options. By default NTFS support is not enabled and if you want to enable it, then you need to tweak the kernel configuration. Try using Google and research what kernel options you need to enable in order to have NTFS support.

Then you need to place these settings in this file:

https://github.com/ivandavidov/minimal/blob/master/src/2_build_kernel.sh

Actually this work has already been done in Ronny Kalusniok's fork of "Minimal Linux Live". You can check his changes here:

https://github.com/ladiko/minimal/blob/master/src/2_build_kernel.sh

Regards,
Ivan Davidov
