### ISSUE TITLE
Support for another libC backend (musl, etc)

### ISSUE THREAD

**Issue by alive4ever** [ivandavidov/minimal#35]
Since this project aims at building small linux image, it would be great to also support small libC backend in addition to GlibC, such as [musl](www.musl-libc.org) or another libc.

**Comment by ivandavidov** [comment]
Actually the project aims at building Linux based ISO image in relatively simple way. Size doesn't really matter. :)

Please read the following blog article where I explain in details why I dropped 'musl' and switched entirely to 'glibc':

http://blog.idzona.com/2016/01/the-future-of-minimal-linux-live.html

I used to maintain an 'experimental' folder which contains 'musl' and some other software pieces till April 2nd this year when I removed this folder in favor of 'glibc'. I originally solved the long bothering DNS issue by using 'musl' on September 15th last year (you can refer to git commit messages) and used to think that 'musl' would be easy to plug in the build infrastructure. However, it turned out I was wrong. :)

In addition, one positive feature of having 'glibc' around is that we can drop any precompiled binaries and (in theory) they should work fine because 'clibc' is the 'de facto' standard for pretty much all Linux based distributions. Otherwise, if we have used any other C library, we would have to recompile the software that we want to use and that's not always possible.

Thank you for your interest in the project and for the suggestion to include another C library. I might do that in the future but for now I'll stick with 'glibc'. Meanwhile, feel free to implement it in your own fork of MLL and please let me know if you make it work. I'll be happy to see the final result!

 I'm closing this issue.
