### ISSUE TITLE
Links: Missing libz.so.1

### ISSUE THREAD

**Issue by AwlsomeAlex** [ivandavidov/minimal#41]
Whenever I try to load Links I get the following error:

`links: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory`

And when I check my /lib and /lib64, the library file is not present. Is there maybe a configuration workaround, or does the dependency HAVE to be added?

**EDIT:** Adding the `--disable-zlib` argument to the configuration to see what happens.

**EDIT 2:** That gave the same error. Any Suggestions?

**Comment by ivandavidov** [comment]
The overlay software compilation process is host OS dependent. Therefore, my intention is to disable the overlay bundles by default since this compilation process may break the overall MLL build process. This needs to be documented before the next release.

Regarding your issue - follow the instructions here and see if you can compile & run links outside of the MLL environment:

http://links.twibright.com/download.php

**Comment by ivandavidov** [comment]
I updated the MLL components with their most recent stable versions. I also updated the Links build process and the ``zlib`` issue should no longer be a problem. I used ``--without-zlib`` which completely ignores ``zlib`` during the build process.

Please check the most recent source code and confirm whether the issue has been fixed.

**Comment by AwlsomeAlex** [comment]
That solved it.
