### ISSUE TITLE
ISO to USB

### ISSUE THREAD

**Issue by AwlsomeAlex** [ivandavidov/minimal#47]
Hello, I'm trying to extract the contents of the .iso image onto a USB so I can install it onto other computers, however most programs format the USB in vFat, which I want to avoid due to OverlayFS not supporting it. Is there a way to 'flash' Minimal Linux Live onto a ext4 USB? I've tried dd, it never works. Also if not, if I were to compile the OverlayFS under 'sparse' instead of 'folder' and lets say I made 20 MB worth of changes **BUT** the Sparse Image is only 10 MB, would it automatically increase, or would it remain 10 MB and delete the other 10 MB?

**Comment by K1773R** [comment]
There is no need to format your device and dd the ISO onto that partition. dd the iso to the device itself. It contains a hybrid (iso9660 and x86 boot sector).

The sparse is just a loop mount. If you only create 10MB loop device, of course you can only store 10MB there (including FS). Also it dosnt grow hence its just like any other block device. A nice way is to move from sparse file to squashfs + tmpfs, but this is something for the future.

**Comment by AwlsomeAlex** [comment]
@K1773R Tried that, it just says that no disk was detected or skips the USB Drive.

**Comment by K1773R** [comment]
do other USB devices work when you start MLL? if not, your USB controller isnt detected due to no driver. if thats the case, you'll have to manually add the controller to .config (not MLL .config)

**Comment by ivandavidov** [comment]
**K1773R** is right - the issue is due to missing USB controller drivers. After all, MLL is just a very basic operating system with default kernel options (slightly tweaked but still very close to default) and as consequence the hardware detection works with very limited hardware.

The solution would be to enable the correct USB controller driver in the kernel's configuration file and then recompile the kernel.

Regarding the installation - using ``dd`` directly on the USB flash will work fine. Another option is to format the USB flash with ext2/3/4, then copy all the files to the USB and then execute ``extlinux --install`` (you need the ``syslinux`` dependency installed on your host OS), just as I have implemented it currently in the [installer](https://github.com/ivandavidov/minimal/blob/master/src/overlay_mll_utils_03_installer.sh).

**Comment by AwlsomeAlex** [comment]
@K1773R Okay, ill try that. @Ivandavidov The thing is, when I run `qemu-system-x86_64 -hda /dev/sdx` after dding the usb drive. It results with an Error while trying to read the CD?

**Comment by ivandavidov** [comment]
"Error while trying to read the CD?" - this could be anything.

@AwlsomeAlex - please have in mind that when have issues and you request help, you should provide as much information as possible:

- Let us know what you try to achieve as final result.
- Describe what you have done in order to achieve this result.
- Describe the outcome of your efforts.
- Provide screenshots and logs.

**Comment by AwlsomeAlex** [comment]
Okay. First I did `sudo dd bs=1M if=minimal.iso of=/dev/sdx` and it ran successfully, then I executed `sudo sync` and after I ran `sudo qemu-system-x86_64 -hda /dev/sdx` and this is what showed up: 
`Booting from Hard Drive... Boot failed: not a bootable disk` and 
`Booting from DVD/CD... Boot Failed: Could not read from CDROM (Code 0003). 
Also the terminal gives the error `WARNING: Image format was not specified for '/dev/sdd' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.`

**Comment by ivandavidov** [comment]
@AwlsomeAlex  - did you try to run qemu with the ``-cdrom`` option pointing to your USB flash device? After all, what you did was to ``dd`` and ISO image directly on your USB flash device and therefore the data on the USB device should be recognizable as ISO image.

**Comment by AwlsomeAlex** [comment]
@ivandavidov Okay, I did that and it actually worked, until another problem arose, a kernel panic with it saying: `---[ end Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)`

**Comment by ivandavidov** [comment]
@AwlsomeAlex - did you try to increase the RAM? For example, if you use ``128M`` then set it to ``256M``. This should solve your issue.

**Comment by AwlsomeAlex** [comment]
@ivandavidov Yep, that works. Thanks. Well now I need to figure out what's wrong with AwlsomeLinux, because it gives that kernel panic regardless. Also it still doesn't boot on physical machines?

**Comment by ivandavidov** [comment]
@AwlsomeAlex  - I'm trying to build a rocket. Which parts do you suggest I should use in order to launch the rocket? :)

Perhaps you should take a look at the kernel's configuration file (.config) for your host operating system (the one where you build MLL) and enable some or all of the kernel options mentioned there. You should be aware that the kernel by itself is not enough. You also need kernel modules + firmware + way to autodetect how/when the lod the modules (e.g. hotplug mechanism via udev or mdev).

I recently committed some changes in the [mincs](https://github.com/ivandavidov/minimal/tree/mincs) branch where I have enabled the defautl kernel modules and the firmware. This might be useful to you.

MLL also supports the option to build kernel from already existing configuration file. I see you have removed this option from your build scripts but you might want to reconsider adding it again because it will allow you to use build and use the same kernel which you are already using on your host machine.

**Comment by AwlsomeAlex** [comment]
Okay, I'll experiment with that. I'll enable firmware and modules and see what happens there. If not I'll play around with the config. Thanks again! One last thing, what is pivot_root? And would that be helpful for my case? I read about it but I don't see a use for it, is that only for the Docker Support?

**Comment by K1773R** [comment]
http://man7.org/linux/man-pages/man2/pivot_root.2.html

**Comment by ivandavidov** [comment]
The last time you said that this stuff looks confusing. Take a look at the comments in issue #45 where I have pointed you to some good documents which you should read before you continue with your experiments.

**Comment by ivandavidov** [comment]
@AwlsomeAlex  - perhaps it will be best to forget about ``udev`` for a while and concentrate on ``mdev`` since the latter is simpler, easier and it is available as BusyBox applet, so you don't need to compile additional stuff.

But first of all - please familiarize yourself about ``chroot``, ``switch_root`` and ``pivot_root``. This particular knowledge is powerful and once you learn this stuff, you will become powerful man.

**Comment by AwlsomeAlex** [comment]
Okay, will do. Thanks. After I implement some more things, I will start playing around with mdev.
