### ISSUE TITLE
GLIBC Fails to Build on x86

### ISSUE THREAD

**Issue by AwlsomeAlex** [ivandavidov/minimal#48]
Hello, I know I've bothered you enough but this time I found something interesting. Whenever Minimal Linux Live tries to build GLIBC on an x86 host, it always fails in the build stage, giving the error 
`Makefile:recipe for target 'io/subdir_lib' failed.`
However further up the log I can find GLIBC throwing out errors when it's trying to compile ../sysdeps/unix/sysv/linux/posix_fallocate.c giving the error
`error: bp cannot be used in asm here`
`}`
`^`
I also installed all of the required dependencies for GLIBC due to me originally thinking that was the problem, but less dependencies are on my x86_64 machine and it builds fine. I also checked the kernel, everything seems to compile (headers). But I'm honestly not sure what's happening. I've provided a build log to help you out so this is less of a guessing game: (Visible problem from Lines 84,141 - 84,165).
[Minimal Linux Live Build Log](http://www.mediafire.com/file/ynlk68mwvzakbhl/build.log)
Thanks.

**Comment by ivandavidov** [comment]
The next time please use some kind of compressed format (eg. ``zip`` or ``tar.gz``) for such long text files and attach the compressed file instead of the original one.

Perhaps you are using old and unsupported versions for some of the dependencies. It seems that you need to do a major upgrade on your x86 machine in order to get the newest build utilities (e.g. GCC and bc).

**Comment by ivandavidov** [comment]
I don't experience the issue on my x86 machine but it seems that this issue has happened before on other x86 builds. This might be related to the issue:

https://patchwork.openembedded.org/patch/118909/

**Comment by AwlsomeAlex** [comment]
That's weird, I have Lubuntu 16.10 freshly installed on a virtual machine, using the Ubuntu Repositories, I'd expect that to be up to date? And its unclear what the problem is, do I have to add that CFLAGS or remove it? Because the only -fno flag im using is '-fno-stack-protector'?

**Comment by ivandavidov** [comment]
It is clear what the problem is - it is well described in the link which I gave earlier, along with explanation when the issue is reproducible.

Like I said - I don't have this issue which means that the issue (at least for now) is on your local machine. You should try to get deeper in the problem and analyze it in order to fix it. Probably the easiest solution would be to install older version of GCC. Or try to use Linux Mint x86 edition in virtual machine and build MLL there.

**Comment by AwlsomeAlex** [comment]
Oh! I see it now. The '-Os' flag needs to be disabled. I'll try and remove it and see if it helps. If not i'll try the patch (even though it didn't seem to work) and if worse comes to worse Ill use Linux Mint x86. Sorry I didn't see that at the top of the message.

**Comment by AwlsomeAlex** [comment]
Okay, It's fine when I use the '-O2' flag instead of the '-Os' flag. Depending on if its '-O1', '-O2' or '-O3' shouldn't be significant right?

**Comment by ivandavidov** [comment]
[Let me Google that for you!](http://lmgtfy.com/?q=gcc+optimization+flags)

**Comment by AwlsomeAlex** [comment]
How convenient. Thanks! I didn't know it was C++ because I thought CFLAGS were only C. Thanks for your help once again!

**Comment by ivandavidov** [comment]
I believe I found better workaround which could be used as permanent solution. Addin this flag to ``CFLAGS`` seems to do the trick:

``-fomit-frame-pointer``

I have already pushed the corresponding change in the shell script.
