### ISSUE TITLE
add the dropbear , it is important function

### ISSUE THREAD

**Issue by jyf007** [ivandavidov/minimal#50]
Dropbear is a relatively small SSH server and client.
https://matt.ucc.asn.au/dropbear/dropbear.html
i have built with options.h as config
[dropbear-options.h.txt](https://github.com/ivandavidov/minimal/files/616528/dropbear-options.h.txt)

**Comment by K1773R** [comment]
uhm. you are aware you just have to enable it in the config then it will be built?

**Comment by jyf007** [comment]
i have built it on some linux release like debian fedora.

**Comment by K1773R** [comment]
you dont get it. MML already supports including of dropbear. check src/.config

**Comment by jyf007** [comment]
I am sorry,i want a multi-call binary

**Comment by ivandavidov** [comment]
@jyf007 - I want [Ke$ha](https://www.google.com/search?q=kesha) and [Anna Kendrick](https://www.google.bg/search?q=anna+kendrick) in my bed tonight but unfortunately this will be only in my dreams. :)

Now seriously - What MLL provides is **build infrastructure** which provides bootable ISO image as final result. The project provides only the bare minimal stuff which is necessary for usable OS. Everything else is beyond the project scope and it may (or may not) be implemented as ``overlay bundles`` in MLL. As @K1773R  already mentioned - the ``dropbear`` ssh server/client is already present in MLL as overlay bundle. However, the build process is highly host machine dependent and that's why by default all such bundles are 'disabled'. Therefore, you need to explicitly enable one or more such bundles in order to include this bundle in MLL.

Regarding Grub2, EFI and so on - I'm thinking about it but this is still highly experimental and mostly only present in my head. :)

**Comment by jyf007** [comment]
i want to add tomcat as product for my company infrastructure

**Comment by ivandavidov** [comment]
In that case I suggest you take a look at the overlay infrastructure and add the Tomcat package as overlay bundle. When I have enough free time I might add it myself but this won't happen in the next few months as I have other business to do.

Meanwhile, If you have troubles adding Tomcat as overlay bundle, you can take a look at the [network view](https://github.com/ivandavidov/minimal/network) and ask another developer to assist you.

**Comment by K1773R** [comment]
accidental reopen?

**Comment by ivandavidov** [comment]
Yes, it seems I have reopened this issue by mistake. I'm closing it now.
