### ISSUE TITLE
USB wifi/bt

### ISSUE THREAD

**Issue by JPB1JPB1** [ivandavidov/minimal#56]
Hello, 
Nice minimal Linux support and version...

Question : can we have few USB wifi dongle for Wireless network after configuring IP, dns, key ...
Same question with Bluetooth and BTLE ...

Keep going... 
Jp

**Comment by K1773R** [comment]
Very likely not. If there would be just 1 small module to build and support them all, maybe. But this isnt a case as supporting all those devices means much more kernel modules build. If you want special modules, just update the kernel config before building MLL. Ie, if you want some of them, build MLL yourself.

**Comment by JPB1JPB1** [comment]
ok but could it be explained how to add the support for one example of each, wifi and Bt/btle, let say one USB TP Link wifi ( 300Mbits or Dual band),  and one USB CSR dual mode bluetooth... 
Just to get any idea with the main modification and how to do it..
Thanks, and keep going..
Jp

**Comment by K1773R** [comment]
You will have to provide a .config file for the kernel. best get the source, run ```make defconfig && run make menuconfig``` and enable the modules you want included.
Then you move said file elsewhere and update MLL's config, more about this here:
https://github.com/ivandavidov/minimal/blob/master/src/.config#L78

**Comment by JPB1JPB1** [comment]
ok, THANKS

**Comment by K1773R** [comment]
once you got a kernel which has the drivers for your device, of course you'd have to add some userspace tools aswell, for example wpa_supplicant. for this you'd have to create a new overlay bundle, which is documented in docs/

**Comment by ivandavidov** [comment]
@JPB1JPB1  - I agree with @K1773R and what he says is exactly what will/should happen:

- I have no intention to add support for any specific hardware.
- You should either add the support for your specific hardware as part of the MLL build process, or create overlay bundle which includes the same support via loadable kernel module.
- You don't really need to recompile the drivers you need from source. If you already have proper driver/module for kernel 4.4.x, you can reuse this driver directly. All you need to do is to add overlay bundle which packs your module and then ``modprobe`` it when MLL starts.

**Comment by ivandavidov** [comment]
Another option - get the kernel configuration from your OS (e.g. Ubuntu or Linux Mint) and use the MLL feature to build new kernel with already prepared configuration, as @K1773R  already mentioned. This will provide you with kernel which supports much broader range of hardware devices. However, currently this _might not_ work for you.

Assuming you have the kernel, you also need to build and pack the modules. Currently this is not part of the official MLL build process. However, there are some MLL forks where you can see how to do that. Or even better - research t yourself.

The same applies for the kernel firmware packages. Currently MLL doesn't build/pack the kernel firmwares but these firmware binary blobs _sometimes_ are required by some specific drivers. So, you need to ensure that you pack the firmware binaries along with the modules.

You also need to implement a device manager (e.g. ``mdev``, ``udev``, ``eudev``, etc.) in order to process hotplug events. The fact that you have all the necessary kernel modules and firmware binaries only guarantees you that the kernel will recognize the hardware once it is available. At this point you need the device manager to properly configure the device.

Finally, as @K1773R already mentioned, you need user space tools in order to work with the device. Again, it is up to you to pack these tools in MLL. Probably the easiest way is to pack the executable binary files, along with their dependencies as separate overlay bundle.

**Comment by JPB1JPB1** [comment]
ok thanks for the information and the basic procedure.. 
Any weblink to explain a bit more if possible how to do it ?
Ok not to support all hardware, only  two or three USB dongles which are identified and running under Linux.. 
The idea is to be able to adapt and add for a dedicated USB hardware, any USB dongle for wireless connection.

Again great MLL, and Thanks
Jp

**Comment by ivandavidov** [comment]
@JPB1JPB1 - please have in mind that we are talking about OS specific things. Don't expect this to be easy. Don't expect to find tutorials for your specific use case. This is operating system, not some generic stuff that every programmer should know it.

That said, I am not aware of a tutorial which explains how to add specific drivers from scratch in Linux based OS. We already provided you with guidelines and at this point your best friend is uncle Google.

One piece of advice - I believe it will be more useful to you if you read about (and understand) the normal MLL build process before you move to more advanced stuff.

**Comment by K1773R** [comment]
The kernel can have a internal udev variant, if you enable it (see my links above).
Regarding docs, i recommend you'd read this first: https://github.com/ivandavidov/minimal/blob/master/src/the_dao_of_minimal_linux_live.txt

**Comment by ivandavidov** [comment]
I'm closing the issue.
