### ISSUE TITLE
network not working outside qemu ?

### ISSUE THREAD

**Issue by jmheneman** [ivandavidov/minimal#63]
Many thanks for MLL! Wonderful way of learning!
When booted from a USB device (the isohybrid version of resulting .iso), the network does work for me.
Apart from lo, ifconfig shows sit0 network device (IPv6-in-IPv4). (no eth0).
Tested on 32bit and 64bit version on different laptops.
(Tested with other linux distro, network works on these.)
Network works within qemu. ifconfig also shows lo and eth0 devices. eth0 has an ip address (given by dhcp, i suppose.)
Thanks in advance for any hints, 
- Jean-Marc (new in GitHub)

**Comment by ivandavidov** [comment]
There is a reason why Minimal Linux Live is called "minimal".

The default build of MLL doesn't add any specific network drivers. This means that by default MLL will use the default network drivers which are part of the default kernel build process. These default network drivers are quite old and they are supported by QEMU, VirtualBox and other VM solutions. This is why the network functionality works in QEMU bit doesn't work outside QEMU.

In order to get your network interface up and running, you need to edit the kernel build configuration and add the network driver which is specific for your machine where you are running MLL. One option is to add the necessary driver in the [kernel build script](https://github.com/ivandavidov/minimal/blob/master/src/02_build_kernel.sh).

**Comment by jmheneman** [comment]
Thanks Ivan. I will dig into this! - Jean-Marc

**Comment by jmheneman** [comment]
(I found out. It is quite simple! Many thanks!)

**Comment by frankmeten** [comment]
> (I found out. It is quite simple! Many thanks!)

How do you did it? where it is?
Thanks

**Comment by frankmeten** [comment]
> There is a reason why Minimal Linux Live is called "minimal".
> 
> The default build of MLL doesn't add any specific network drivers. This means that by default MLL will use the default network drivers which are part of the default kernel build process. These default network drivers are quite old and they are supported by QEMU, VirtualBox and other VM solutions. This is why the network functionality works in QEMU bit doesn't work outside QEMU.
> 
> In order to get your network interface up and running, you need to edit the kernel build configuration and add the network driver which is specific for your machine where you are running MLL. One option is to add the necessary driver in the [kernel build script](https://github.com/ivandavidov/minimal/blob/master/src/02_build_kernel.sh).

 Could you give me some code snippet or link of "necessary driver "
Thanks

**Comment by jmheneman** [comment]
Hello Frank,
I am sorry for the delay. It has been more than 2 years I did not worked on that project.
But I remember that I had to add drivers into the kernel by configuring it.
According to my old "minimal" notes, the command is 
`make menuconfig`
Take a look in the .config to be sure.
Still according to my notes, I had success with b44 network drives bcm4401, atl1e and r8187se but you "mileage" may vary. lshw may be helpful on the target machine. (I had some old test laptops.)
Another note to myself says that I had to 
edit the main .config to set `PREDEF...KERNEL=true` (instead of false)
and Modify kernel.config with make menuconfig thru the .config located under work/kernel/linux-x.y.z/ (needs ncurses-dev)
I hope that tips will permit you to achieve what you want.
Sorry... I cannot be more precise that this. - Jean-Marc
