### ISSUE TITLE
Bundles ignore sysroot

### ISSUE THREAD

**Issue by bauen1** [ivandavidov/minimal#71]
Multiple packages (partially) ignore the glibc sysroot and compile using the host systems libraries and includes.
One example would be the links package.

nweb example on the linker problem:
```bash
gcc --verbose $CFLAGS --sysroot=$MAIN_SRC_DIR/work/glibc/glibc_prepared $SRC_DIR/nweb23.c -o nweb
```
to
```bash
gcc --verbose -Wl,--verbose -Wl,--sysroot=$MAIN_SRC_DIR/work/glibc/glibc_prepared -L =/lib -L =/lib64 $CFLAGS --sysroot $MAIN_SRC_DIR/work/glibc/glibc_prepared $SRC_DIR/nweb23.c -o nweb
```
The second tells the linker the sysroot too and where to search for libraries (`-L =/lib -L =/lib64` is very important)

**Comment by ivandavidov** [comment]
Good catch!

I need to research deeper how easy (or hard) it would be to improve the build process of the currently available overlay bundles and if it is possible to introduce general fix, e.g. perhaps set some global shell properties which will guide GCC...

**Comment by bauen1** [comment]
I looked around in gcc and came up with a very very ugly solution that doesn't link / interact with the host in any way (part of bundle.sh for nweb):

```bash
cd $MAIN_SRC_DIR/work/overlay/nweb
# our sysroot
SYSROOT="$MAIN_SRC_DIR/work/glibc/glibc_prepared"

# gcc has a "internal" path that needs to be added to find the static versions of libgcc_*
GCC_INTERNAL_PATH=$(dirname $(gcc -print-libgcc-file-name))

# create a specs file to overwrite /usr/lib and so on
# this specs file should ideally reside in src/work/sysroot.specs along with the sysroot
cat << CEOF > test.specs
*link_libgcc:
-L$SYSROOT/lib -L$SYSROOT/lib64 -L$SYSROOT/usr/lib -L$SYSROOT/usr/lib64 -L$SYSROOT/usr/local/lib -L$SYSROOT/usr/local/lib64 -L$GCC_INTERNAL_PATH
CEOF

# -specs could maybe be moved to CFLAGS
CC="gcc -specs=$PWD/test.specs"

# -nostdlib prevents ld's linker script from adding /usr/lib
LDFLAGS="-Wl,--verbose,-nostdlib"

# we don't have gcc-libs for our guest/minimal system so we have to force static linking for libgcc
CFLAGS="--verbose -static-libgcc"

set -x

#strace \
$CC $CFLAGS $LDFLAGS $SRC_DIR/nweb23.c -o nweb

# uncomment strace and run
#  ./bundle.sh &>/dev/fd/1 | grep "[^d]/usr/lib" --color=auto
# to see that it doesn't access host files in /usr/lib in anway (apart from the compilers own files in /usr/lib/gcc/...)
```

Since we already have to redo the sysroot, what about moving the sysroot from `src/work/glibc/glibc_prepared` to `src/work/sysroot` so future libraries can be added easily (and maybe solve the extra flags for bundles that depend on each other)

**Comment by ivandavidov** [comment]
Good research! The only drawback I see for now is that this complicates the build process quite a lot. Nevertheless, this is an interesting approach and personally I am willing to experiment with this.

The idea to move the ``sysroot`` to its own ``work`` folder is OK and it actually makes sense.

Implementing this might complement very well with #58 and more precisely the part where custom linker needs to be added as separate step in MLL. This also leaves room for further size optimizations where the object "stripping" could be done on linker level instead of relying on the ``strip`` command.

Just as a side note - I believe this should be done as a best effort to support the overlay bundle build structure. The MLL build structure should not be affected by these changes. I know from personal experience that playing with the GCC related shell variables easily leads to compilation issues which are hard to find/debug and I would like to keep the original MLL build process as simple as possible. At least for now.

The above note does not apply for the overlay bundles and there we can do all kinds of experimental stuff and optimizations.

**Comment by bauen1** [comment]
Look at https://github.com/bauen1/minimal/tree/misc-changes

**Comment by ivandavidov** [comment]
Yes, that's exactly what I had in mind with my last comment. Feel free to submit PR when you believe it is ready. I'll review and test it as soon as possible.
