### ISSUE TITLE
Provide overlay bundle for kernel modules and firmware

### ISSUE THREAD

**Issue by ivandavidov** [ivandavidov/minimal#77]
Right now MLL provides just minimal kernel with default functionality. It will be good to "upgrade" this by adding kernel modules and firmware. Building and packing the default modules and firmware has been implemented in the [mincs branch](https://github.com/ivandavidov/minimal/tree/mincs/src) and this functionality can be implemented as overlay bundle.

The bundle should also provide [autorun](https://github.com/ivandavidov/minimal/commit/c915716a153b1bc175b4787400cf816c19212056#diff-6ef13c1e01500d8db71f669d6bbbc010) script which handles properly the [mdev setup](https://git.busybox.net/busybox/plain/docs/mdev.txt).

**Comment by robertmartin** [comment]
I'm not so excited about overlays, but I agree about the autorun.

Thank you for your efforts, I appreciate having MLL available.

On Jul 19, 2017 12:54 PM, "Ivan Davidov" <notifications@github.com> wrote:

Right now MLL provides just minimal kernel with default functionality. It
will be good to "upgrade" this by adding kernel modules and firmware.
Building and packing the default modules and firmware has been implemented
in my mincs branch <https://github.com/ivandavidov/minimal/tree/mincs/src>
and this functionality can be implemented as overlay bundle.

The bundle should also provide autorun
<https://github.com/ivandavidov/minimal/commit/c915716a153b1bc175b4787400cf816c19212056#diff-6ef13c1e01500d8db71f669d6bbbc010>
script which handles properly the mdev configuration
<https://git.busybox.net/busybox/plain/docs/mdev.txt>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ivandavidov/minimal/issues/77>, or mute the thread

**Comment by ivandavidov** [comment]
The in-kernel firmware support has been [dropped](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b38923a068c10fc36ca8f596d650d095ce390b85) in version 4.14 and as result ``make firmware_install`` no longer works.

In this case MLL can still provide the default kernel modules + some basic ``mdev`` configuration. However, if some of these modules require firmware blob (which is unlikely but I haven't researched it), this module most probably would fail to load. The default kernel modules are the following:

* thermal
* efivars
* ipv4/netfilter
* ipv6/netfilter
* netfilter

Most probably these modules won't be useful in MLL due to lack of proper userland tools (e.g. iptables, efibootmgr) but it is still good to provide them as overlay bundle. Note that the 'thermal' module may not load depending on the machine where MLL is running (check '/sys/class/thermal' and 'dmesg | grep therm').

**Comment by ivandavidov** [comment]
The firmware blobs can be packaged from the [linux-firmware](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/README) Git repository with the following command:

``make DESTDIR=<some/directory/here> install``

This produces normal ``/lib/firmware`` structure in ``DESTDIR``. However, the produced directory is way too big (200+ MB) and it seems to contain lots of artifacts that are not firmware blobs (e.g. additional Makefiles in subdirectories). This makes me think that there are other steps that has to be executed before the firmware packaging. Nevertheless, the final size of all prouced firmware blobs will still be way too big and it doesn't make sense to package it in MLL.

**Note:** MLL could provide brief documentation in the overlay bundle that all firmware blobs can be found in the above mentioned Git repository.

**Comment by ivandavidov** [comment]
This feature has been implemented [here](https://github.com/ivandavidov/minimal/commit/3768275daafc8679c66232cd2b49693a562e434d). The ``mdev`` hotplug manager works fine and applies default permissions ``660`` (instead of ``600``) on device files. It has been tested with external USB flash drive which has been detected by the MLL kernel and the corresponding ``/dev/sda`` file has been processed by 'mdev'.

I'm closing this issue.
