### ISSUE TITLE
command `time` only in bash shell

### ISSUE THREAD

**Issue by mudongliang** [ivandavidov/minimal#86]
In my Debian Testing, `/bin/sh` -> `/bin/dash`.
time is one builtin command for `/bin/bash`, not `/bin/dash`. So when I execute "time" in `sh`(dash), it reports error - "/bin/sh: 1: time: not found"

**Comment by ivandavidov** [comment]
Do you have ``/usr/bin/time`` on your machine? In this case you could create temporary alias which points to this particular binary. Another option is to remove all ``time`` occurrences in the scripts since they are there only for logging/debugging purposes.

As a long term solution, I might update the shebang in all build scripts to point to ``/bin/bash`` since 'bash' is pretty much available on all Linux distros.

**Comment by mudongliang** [comment]
```
$ which time
$ whereis time
time: /usr/include/time.h /usr/share/man/man3/time.3am.gz /usr/share/man/man2/time.2.gz /usr/share/man/man7/time.7.gz
```
There is not `time` executable command in my system.

**Comment by K1773R** [comment]
as already pointed out, you can remove the time commands in the script. its just for measuring how long each step takes.

**Comment by mudongliang** [comment]
I can remove `time` from script. However, should we modify the shell script in the repo by removing `time`? But I don't think it's a good idea. If I only want to solve this problem, it is simple and there are many solutions.

**Comment by yetanothergeek** [comment]
What if you just make an empty alias for time:
alias time=

**Comment by mudongliang** [comment]
It is OK.

**Comment by ivandavidov** [comment]
PR #91 fixes this. I'm leaving the issue opened because I haven't tested it yet (it should work smoothly).

**Comment by ivandavidov** [comment]
I'm closing this issue.
