### ISSUE TITLE
Get DNS working

### ISSUE THREAD

**Issue by prologic** [ivandavidov/minimal#9]
I notice DNS doesn't work. We should get this working. I'm not sure what's involved yet by reading http://lists.busybox.net/pipermail/busybox/2001-November/005103.html it looks like we either have to change some compile options for busybox or add in uclibc?

**Comment by cirosantilli** [comment]
Networking newb here:

- where you able to get any networking working at all? E.g.: `wget google.com` or a direct IP `wget 216.58.211.78` or something else?
- What would DNS allow us to do? It would allow to do `wget google.com` instead of just the direct IP?

**Comment by ivandavidov** [comment]
The DNS issue is due to very old architectural issues with static linking of "glibc" and unfortunately this issue affects directly the DSN functionality. There may be other broken bits which are affected due to this issue.

The only reasonable solution is to migrate to another C library like "uclibc" or "musl". Until then we have LAN network support on IP level which is sufficient for DHCP.

**Comment by ivandavidov** [comment]
Good news - I managed to get around the nasty DNS problem. I had to use musl-libc instead of glibc and unfortunately I had to apply several hacks both in BusyBox and musl-libc. The good news is that all of this stuff can be automated but two or three of these hacks which *might* not work on all environments.

Here is what I've got so far:

![image](https://cloud.githubusercontent.com/assets/8343716/9886808/e650c0da-5bf4-11e5-921f-ab0e2bc19582.png)

Looks good to me! :)

**Comment by cirosantilli** [comment]
Great news!!

**Comment by ivandavidov** [comment]
I just pushed my latest changes. The whole build process now includes 3 more steps:

1) Get musl-libc from the official website.
2) Build musl-libc and install it locally.
3) Patch musl-libc in order to build BusyBox smoothly.

The idea is to use the kernel headers from the newly downloaded kernel but this approach currently doesn't work. Another possible solution is to use the headers which are already available on the host machine. However, this might not work well on all environments. Third possible approach is to patch BusyBox and leave musl untouched. 

The build process for BusyBox has been changed as well and two applets have been disabled due to compilation issues (this should be double-checked).

**Comment by ivandavidov** [comment]
The experimental folder "musl-busybox" reuses the headers from the downloaded kernel and the generated ISO image is fully functional, including the network functionality. You should try using the scripts from this experimental folder.

**Comment by jtloper1** [comment]
I just built from musl-busybox. Will not ping google.com

**Comment by ivandavidov** [comment]
1) Did you try any other functionality, e.g. wget and traceroute?
2) Do you have some kind of firewall? If you are running from VM, there might be some firewall restrictions.
3) Are you sure your "Minimal Linux Live" distro gets its own IP address via DHCP?

**Comment by jtloper1** [comment]
I am in the middle of another build right now. I am running vbox. Will post
screen shots.

**Comment by jtloper1** [comment]
Seems to be working now. Thanks

**Comment by ivandavidov** [comment]
The experimental folder 'glibc-busybox' solves the DNS issue and there are no kernel header collisions. However, the overall build is now ~32MB and it takes ~256MB RAM to run. And it may not work on 64bit machines (I've tested it on 32bit machine).

**Comment by ivandavidov** [comment]
The latest published stable release '03-Apr-2016' fixes the problem and I'm closing the issue.
